### ISSUE TITLE
Error on asset_manifest_backup

### ISSUE THREAD

**Issue by aaronshiphawk** [capistrano/rails#33]
Commit bfd01c9 removed the .json suffix from the assets_manifest_backup. This produces an error when deploying on my Ubuntu environment. Suggest changing assets_manifest_backup to assets_manifest.backup

DEBUG [7813d7de] Command: cd /home/deployer/discourse-production/releases/20131115183147 && ( RAILS_ENV=production cp /home/deployer/discourse-production/releases/20131115183147/public/assets/manifest* /home/deployer/discourse-production/releases/20131115183147/assets_manifest_backup )
DEBUG [7813d7de]    cp: 
DEBUG [7813d7de]    target `/home/deployer/discourse-production/releases/20131115183147/assets_manifest_backup' is not a directory

**Comment by mrreynolds** [comment]
Happened for me as well, I fixed it in #105 (PR).

**Comment by derickhoganpimenta** [comment]
HI, guys.

My solution is:
Delete shared/public/assets and put the manifest.json file in /public directory.

It's work for me

**Comment by kirs** [comment]
Solved in #105 now. Thanks @mrreynolds and @miry!

**Comment by t-anjan** [comment]
I have the exact same issue. This PR, though a good idea, did not solve the problem for me. After debugging for a while, I figured out that the error I was getting was because the pre-compilation was not even generating a `manifest*` file. It looks like the new name for the manifest file is `.sprockets-manifest*`.

**Comment by Majkeen** [comment]
I have the exact same issue. And like @t-anjan i get a `.sprockets-manifest*` not a `.manifest*` file.

**Comment by faucct** [comment]
Doubling that. Adding the thing to the deploy.rb is a quick fix for that.
````
Rake::Task['deploy:assets:backup_manifest'].clear_actions
namespace :deploy do
  namespace :assets do
    task :backup_manifest do
      on roles(fetch(:assets_roles)) do
        within release_path do
          execute :cp,
                  release_path.join('public', fetch(:assets_prefix), '.sprockets-manifest*'),
                  release_path.join('assets_manifest_backup')
        end
      end
    end
  end
end
````

**Comment by kirs** [comment]
@Majkeen @faucct @t-anjan please, check out https://github.com/capistrano/rails/issues/111#issuecomment-92745739
